spring:
  ssl:
    bundle:
      pem:
        emoji-api:
          keystore:
            certificate: "classpath:emojiclientcertlocal.pem"
            private-key: "classpath:client-private-key.pem"
            private-key-password: "password"
          truststore:
            certificate: "classpath:emojiapicertlocal.pem"
