spring:
  ssl:
    bundle:
      pem:
        consumer-mtls:
          keystore:
            certificate: "classpath:consumercert.pem"
            private-key: "classpath:consumer-private-key.pem"
            private-key-password: ${private-key-passwd}
          truststore:
            certificate: "classpath:apicert.pem"
